### ISSUE TITLE
IS_MSO Packet error

### ISSUE THREAD

**Issue by ghost** [alexmcbride/pyinsim#1]
```
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 79, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 435, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\site-packages\pyinsim\core.py", line 260, in handle_read
    self._dispatch_to._handle_tcp_read()
  File "C:\Python27\lib\site-packages\pyinsim\core.py", line 467, in _handle_tcp_read
    self._handle_insim_packet(data)
  File "C:\Python27\lib\site-packages\pyinsim\core.py", line 496, in _handle_insim_packet
    packet = _PACKET_MAP[ptype]().unpack(data)
  File "C:\Python27\lib\site-packages\pyinsim\insim.py", line 630, in unpack
    self.Msg = struct.unpack('%dsx' % self.Size - 9, data[8:])
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```

**Comment by alexmcbride** [comment]
Fixed.
